#!/bin/sh

find_device() {
	ATTR_FILE=""
	for file in /sys/class/usb/osrfx2_[0-9]; do
		if [ $file = "/sys/class/usb/osrfx2_[0-9]" ]; then
			echo "No sysfs file"
			exit
		fi
		ATTR_FILE=$file/device/switches
	done

	if [ "$ATTR_FILE" = "/device/switches" ]; then
		echo "Can't find OSR USB-FX2 device"
		exit
	fi
}

find_device
./switch_events

while `/bin\/true`
do
	VALUE=`cat $ATTR_FILE 2>/dev/null`
	if [ $? -ne 0 ]; then
		find_device
	fi
	echo "$VALUE"
	./switch_events
done

